services:
  pritunldb:
    image: mongo:latest
    container_name: pritunldb
    hostname: pritunldb
    networks:
      - internal
    volumes:
      - ./db:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - internal
      - proxy
    links:
      - pritunldb:mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1194:1194
      - 1194:1194/udp
      - 1195:1195/udp
    expose:
      - 9700
    environment:
      - TZ=UTC
      - MONGODB_URI=mongodb://pritunldb:27017/pritunl
      - REVERSE_PROXY=true
    labels:
      - traefik.enable=true
      ## Traefik v1 settings:
#      - traefik.backend=pritunl
#      - traefik.frontend.rule=Host:<HOSTNAME>
#      - traefik.port=9700
#      - traefik.docker.network=proxy
#      - traefik.enable=true
      ## Traefik v2+:
      - traefik.docker.network=proxy
      ## Traefik v2 HTTP Routers
      - traefik.http.routers.pritunl-rtr.entrypoints=https
      - traefik.http.routers.pritunl-rtr.rule=Host(`<HOSTNAME>`)
      - traefik.http.routers.pritunl-rtr.tls=true
      ## Traefik v2 Middlewares
#      - traefik.http.routers.pritunl-rtr.middlewares=chain-no-auth@file # No Authentication
#      - traefik.http.routers.pritunl-rtr.middlewares=chain-basic-auth@file # Basic Authentication
#      - traefik.http.routers.pritunl-rtr.middlewares=chain-oauth@file # Google OAuth 2.0
      ## Traefik v2 HTTP Services
      - traefik.http.routers.pritunl-rtr.service=pritunl-svc
      - traefik.http.services.pritunl-svc.loadbalancer.server.scheme=http
      - traefik.http.services.pritunl-svc.loadbalancer.server.port=9700

networks:
  proxy:
    external:
      name: proxy
  internal:
    driver: bridge
    internal: true

